version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_container
    environment:
      POSTGRES_DB: campus_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'

  smartcampus:
      build: .
      ports:
        - "5000:5000"
      environment:
        - DATABASE_URL=postgresql://postgres:postgres@postgres_container:5432/campus_db
      depends_on:
        - postgres